"""Helm ``Chart.yaml`` dependency-version in-place rewriter.

Bumper-orchestrator emits :class:`RewriteEdit` with
``locator = chart_name`` (e.g. ``"postgresql"``); the rewriter
finds the dependency block under ``dependencies:`` whose
``name:`` matches the locator and rewrites that block's
``version:`` field.

The rewrite is line-shape-based (regex, not YAML parse+round-
trip) so the surrounding formatting / comments / indentation
stay intact — important because operator-edited Chart.yaml files
often have alignment and operator-comments that round-tripping
through ``yaml.safe_dump`` would destroy."""

from __future__ import annotations

import logging
import re

from . import RewriteEdit, RewriteResult, register, rewrite_file_with
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

logger = logging.getLogger(__name__)


def _is_chart_yaml(path: Path) -> bool:
    """Match ``Chart.yaml`` exactly (not ``Chart.lock`` — the
    lockfile gets regenerated by ``helm dep update`` after we
    bump Chart.yaml)."""
    return path.name == "Chart.yaml"


@register(predicate=_is_chart_yaml)
def rewrite_chart_yaml(
    path: Path, edits: list[RewriteEdit],
) -> list[RewriteResult]:
    """Apply chart-version edits to a Chart.yaml in place."""
    return rewrite_file_with(path, edits, _apply_one_chart)


def _apply_one_chart(
    text: str, edit: RewriteEdit,
) -> tuple[str, RewriteResult]:
    """Apply one chart-version edit.

    Strategy: find ``- name: <locator>`` inside the
    ``dependencies:`` block, then walk forward to find the
    matching ``version:`` line at the same indent. This
    side-steps YAML's "what's the next list item" ambiguity by
    finding both lines syntactically (regex) rather than
    structurally (yaml parse).
    """
    locator = re.escape(edit.locator)
    # Match ``- name: <locator>`` line then the following
    # ``version: <value>`` line at the same indent. The two
    # lines may appear in either order within the dep block;
    # try both shapes.
    #
    # Intermediate lines between the two anchors: each iteration
    # consumes EXACTLY ONE non-blank, non-list-item line. The previous
    # spelling ((?:\s*(?!-).+\n)*?) let \s* span newlines and .+ eat
    # spaces, giving every filler line many ambiguous splits — overall
    # match FAILURE (a dep block with filler lines and no same-indent
    # version: line) backtracked exponentially (~x16 per two lines;
    # a 30-line block from a hostile Chart.yaml hung the harden/bump
    # run without any timeout). One-line-per-iteration is linear. The
    # boundary is STRICTER than before: a `-` list item or a blank
    # line hard-stops the window (the old spelling could backtrack
    # `\s*` to zero and accidentally cross a `-` line into ANOTHER
    # dep's version — a cross-dep mis-splice held back only by the
    # value_mismatch guard). A dep whose version follows a nested
    # list (tags:/condition:) now declines with not_found — the
    # visible, refusal-direction trade.
    between = r"(?P<between>(?:(?![^\S\n]*(?:-|\n))[^\n]*\n)*?)"
    # Shape A: name-then-version
    pat_name_first = re.compile(
        rf"^(?P<indent>\s+)- name:\s*{locator}\s*(?P<namecomment>#[^\n]*)?\n"
        rf"{between}"
        rf"(?P<prefix>(?P=indent)\s+version:\s*[\"']?)"
        rf"(?P<ver>[^\s\"'#]+)"
        rf"(?P<suffix>[\"']?\s*(?:#[^\n]*)?\n)",
        re.MULTILINE,
    )
    # Shape B: version-then-name
    pat_version_first = re.compile(
        rf"^(?P<indent>\s+)(?P<vprefix>- version:\s*[\"']?)"
        rf"(?P<ver>[^\s\"'#]+)"
        rf"(?P<vsuffix>[\"']?\s*(?:#[^\n]*)?\n)"
        rf"{between}"
        rf"(?P<nline>(?P=indent)\s+name:\s*{locator}\s*(?:#[^\n]*)?\n)",
        re.MULTILINE,
    )
    # A Chart.yaml can declare the SAME chart several times (aliased
    # entries — e.g. two redis instances off one chart). Verdicts are
    # computed across ALL entries and every one still at the old
    # value is bumped: a first-match ``count=1`` substitution bumped
    # one alias and left its twin on the vulnerable version while the
    # run reported applied. Each entry matches exactly one shape
    # (its own line order), so the two match sets are disjoint.
    matches = list(pat_name_first.finditer(text))
    matches += list(pat_version_first.finditer(text))
    if not matches:
        return text, RewriteResult(
            edit=edit, applied=False, reason="not_found",
        )
    values = [m.group("ver") for m in matches]
    needs_bump = [
        m for m in matches
        if m.group("ver") == edit.old_value
        and m.group("ver") != edit.new_value
    ]
    if not needs_bump:
        if all(v == edit.new_value for v in values):
            return text, RewriteResult(
                edit=edit, applied=False, reason="no_change",
            )
        stray = next(v for v in values if v != edit.new_value)
        return text, RewriteResult(
            edit=edit, applied=False,
            reason=(
                f"value_mismatch: file has {stray!r}, "
                f"plan expected {edit.old_value!r}"
            ),
        )
    # Replace each entry's version-value span directly (back-to-front
    # so earlier offsets stay valid) — everything around the value,
    # including comments and quoting, is preserved verbatim.
    new_text = text
    for m in sorted(needs_bump, key=lambda m: m.start("ver"),
                    reverse=True):
        new_text = (
            new_text[:m.start("ver")]
            + edit.new_value
            + new_text[m.end("ver"):]
        )
    stray_values = sorted(
        set(values) - {edit.old_value, edit.new_value})
    reason = "applied"
    if stray_values:
        reason = (
            f"partial: {len(needs_bump)} entrie(s) bumped; other "
            f"value(s) left in place: {stray_values!r}"
        )
    return new_text, RewriteResult(
        edit=edit, applied=True, reason=reason,
    )


