"""Vendored / generated-code triage detector.

Classifies FILES as vendored or machine-generated so the audit triage
layer can route their functions into the cheap skip/glance tier
instead of full hypothesis review. Motivating incident: an audit of a
target that vendored Eurydice-generated ML-KEM/ML-DSA headers and a
single-header PKCS#11 constant catalog sent thousands of generated
one-line functions through full hypothesis review at ~$0.52/function
— the demotions were correct, but the review budget was spent on code
no human wrote.

Signals are generic generator/vendoring SHAPES, never a hardcoded
project list:

* generator banners in the file's comment header ("Generated by …",
  "@generated", "DO NOT EDIT", "generated with the following
  revisions", …) — comment-anchored, same doctrine as
  ``core.inventory.exclusions.is_generated_file``;
* generated-output filename conventions (protoc / bindgen / stringer
  / lex-yacc output shapes);
* vendored-path conventions (``vendor/``, ``third_party/``,
  ``external/``, ``node_modules/``, …);
* formatting signatures of generated code (enormous constant tables;
  swarms of one-line functions with near-zero comment variance).

Trust model (mirrors the inventory builder's anti-evasion rule): the
in-file banner is TARGET-CONTROLLED text. A banner alone therefore
NEVER earns the skip tier — only the glance tier (the function still
gets a cheap LLM look, and every decision leaves a suppressions.jsonl
record; nothing becomes invisible). The skip tier requires the
banner to be corroborated by an independent generated-shaped path or
filename (``core.inventory.exclusions.generated_marker_corroborated``
— the same corroboration the inventory layer demands before excluding
a file outright). Structural evidence (tables / one-liner swarms) is
also target-controlled and maps to the glance tier only.

Routing itself lives in :func:`core.audit.triage.classify_function`;
this module only produces per-file verdicts.
"""

from __future__ import annotations

import logging
import re
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any

from core.inventory.exclusions import generated_marker_corroborated

from ._util import safe_join

logger = logging.getLogger(__name__)

KIND_GENERATED = "generated"
KIND_VENDORED = "vendored"

# Banner scan window: wider than the inventory builder's 10 lines —
# generator banners routinely sit BELOW a license block (the Eurydice
# / libcrux revision block is ~20-30 lines in). Still bounded so a
# mid-file prose mention ("the report is generated by the server")
# cannot classify a whole file.
_BANNER_MAX_LINES = 100
_BANNER_MAX_BYTES = 8192

# Comment-line shapes for the languages the inventory extracts from
# (same set as core.inventory.exclusions.is_generated_file): markers
# must appear INSIDE a comment line to count — a string literal or
# prose mention never classifies.
_COMMENT_RE = re.compile(r"^\s*(#|//|/\*|\*|--|<!--)")

# Generic generator-banner shapes (seeds — deliberately tool-agnostic;
# "generated by protoc" and "Generated by KaRaMeL" match the same
# pattern, no per-project list).
#
# Two tiers. ANCHORED markers must match at the START of the comment
# text (after the comment leader): a real generator banner declares
# itself ("Code generated by protoc…", "Generated by KaRaMeL"), while
# prose merely MENTIONS generation mid-sentence ("…wire format). Code
# generated by the compiler uses these classes", "events generated by
# the engine") — both real hand-written files a floating match wrongly
# classified. FLOATING markers ("DO NOT EDIT", "@generated") are
# explicit editor directives, matched anywhere in the comment line
# (house precedent: core.inventory.exclusions.GENERATED_MARKERS).
_ANCHORED_BANNER_MARKERS: list[re.Pattern[str]] = [
    re.compile(r"auto[- ]?generated", re.IGNORECASE),
    re.compile(r"automatically generated", re.IGNORECASE),
    re.compile(r"machine[- ]generated", re.IGNORECASE),
    re.compile(r"mechanically generated", re.IGNORECASE),
    re.compile(r"(?:code|file) (?:was )?generated by\s*\S+", re.IGNORECASE),
    re.compile(r"generated by\s+\S+", re.IGNORECASE),
    re.compile(r"generated from\s+\S+", re.IGNORECASE),
    re.compile(
        r"this (?:file|code|header) (?:was|is|has been) "
        r"(?:automatically |mechanically )?generated",
        re.IGNORECASE,
    ),
    re.compile(r"generated with the following", re.IGNORECASE),
    re.compile(r"this file is generated", re.IGNORECASE),
]
# Vendored-provenance banners: an upstream import pinned to a
# revision/version ("Extracted from libcrux revision c46481…",
# "Imported from tinyxml2 version 9.0"). BOTH the verb-from-project
# shape AND a pin token are required — prose like "extracted from the
# packet" never carries "revision <id>", so the family stays precise.
# Target-controlled text: earns the vendored GLANCE tier only, never
# a skip (same trust model as every other banner).
_VENDORED_BANNER_MARKERS: list[re.Pattern[str]] = [
    re.compile(
        r"(?:extracted|imported|copied|derived|adapted) from\s+\S+.{0,40}?"
        r"(?:revision|commit|version|snapshot|release|tag)[:\s]\s*\S+",
        re.IGNORECASE,
    ),
]

_FLOATING_BANNER_MARKERS: list[re.Pattern[str]] = [
    re.compile(r"do not edit", re.IGNORECASE),
    re.compile(r"do not modify(?: this file)? (?:by hand|manually)",
               re.IGNORECASE),
    re.compile(r"@generated"),
]

# Comment leader to strip before anchored matching: //, #, /*, *, --,
# <!-- plus surrounding whitespace.
_COMMENT_LEADER_RE = re.compile(r"^\s*(?:/\*+|//+|#+|--+|<!--|\*+)\s*")

# Generated-output filename conventions. Filename shape counts as
# independent corroboration (house rule: _GENERATED_NAME_RE in
# core.inventory.exclusions) — these files earn KIND_GENERATED with
# corroborated=True even without a readable banner.
_GENERATED_SUFFIXES: tuple[str, ...] = (
    "_pb2.py", "_pb2_grpc.py",
    ".pb.go", ".pb.h", ".pb.cc", ".pb-c.c", ".pb-c.h",
    ".generated.go", ".generated.h", ".generated.cs",
    ".gen.ts", ".gen.js", ".gen.go",
    "_generated.rs", "_generated.go", "_generated.py",
    ".g.dart", ".g.cs",
    "lex.yy.c", "y.tab.c", "y.tab.h",
)

# Vendored-path directory conventions (matched against DIRECTORY
# segments only — a file named ``vendor.c`` is not vendored).
_VENDORED_SEGMENTS = frozenset({
    "vendor", "vendors", "vendored", "_vendor",
    "third_party", "thirdparty", "third-party",
    "3rdparty", "3rd_party", "3rd-party",
    "external", "externals", "extern",
    "deps", "node_modules", "bundled", "subprojects",
})

# ── Structural signatures ─────────────────────────────────────────────
#
# Constant-table shape: a file that is mostly numeric-literal rows or
# constant #defines (PKCS#11-style catalogs, codec tables, unicode
# tables). Thresholds are deliberately high so hand-written code that
# merely CONTAINS a big table never classifies: the table must
# dominate the whole file.
_TABLE_MIN_LINES = 200
_TABLE_MIN_RATIO = 0.5

_NUM = r"(?:0[xX][0-9a-fA-F]+[uUlL]*|-?\d+(?:\.\d+)?[uUlLfF]*|'(?:\\.|[^'\\])')"
_TABLE_LINE_RE = re.compile(
    rf"^\s*\{{?\s*{_NUM}(?:\s*,\s*{_NUM})*\s*,?\s*\}}*\s*,?\s*$"
)
_DEFINE_CONST_RE = re.compile(
    r"^\s*#\s*define\s+\w+\s+\(?\s*(?:0[xX][0-9a-fA-F]+|\d+)"
)

# One-liner-swarm shape: dozens of tiny functions with near-zero
# comment density (Eurydice / bindgen / protoc output shape). Both
# thresholds must hold; hand-written accessor headers usually carry
# comments and rarely reach the function-count floor.
_SWARM_MIN_FUNCS = 30
_SWARM_TINY_SLOC = 6
_SWARM_TINY_FRACTION = 0.8
_SWARM_MAX_COMMENT_FRACTION = 0.05

# Full-file read cap for the structural pass (matches the spirit of
# the inventory builder's stat-then-bound read).
_MAX_STRUCTURE_BYTES = 2 * 1024 * 1024

_FUNCTION_KINDS = frozenset({"function", "method"})


@dataclass(frozen=True)
class VendorVerdict:
    """Per-file vendored/generated classification.

    ``kind``          — ``generated`` (explicit generator provenance)
                        or ``vendored`` (path convention / structural
                        shape).
    ``signal``        — ``banner`` / ``extension`` / ``path`` /
                        ``structure`` / ``checklist``.
    ``detail``        — human-readable evidence for reasons strings
                        and suppressions.jsonl records.
    ``corroborated``  — for KIND_GENERATED: True when an independent
                        generated-shaped path/filename backs the
                        banner (house corroboration rule). Only
                        corroborated generated files may reach the
                        skip tier; everything else is glance-bound.
    """

    kind: str
    signal: str
    detail: str
    corroborated: bool = False


def detect_vendored_files(
    gaps: Sequence[dict[str, Any]],
    *,
    target_path: Path | None = None,
    checklist: dict[str, Any] | None = None,
) -> dict[str, VendorVerdict]:
    """Classify every distinct gap file. Returns ``{file: verdict}``.

    ``checklist`` (optional) supplies the inventory builder's own
    ``generated_marker: "uncorroborated"`` flags so banner evidence
    the builder already found is consumed without re-reading files.
    Best-effort per file: an unreadable file simply contributes no
    banner/structure evidence (path and filename signals still apply).
    """
    by_file: dict[str, list[dict[str, Any]]] = {}
    for gap in gaps:
        file_path = gap.get("file", "")
        if file_path:
            by_file.setdefault(file_path, []).append(gap)

    marker_flags = _checklist_marker_flags(checklist)

    verdicts: dict[str, VendorVerdict] = {}
    for file_path, file_gaps in by_file.items():
        text = _read_file(file_path, target_path)
        verdict = classify_file(
            file_path,
            text,
            file_gaps,
            checklist_marker=marker_flags.get(file_path, ""),
        )
        if verdict is not None:
            verdicts[file_path] = verdict
    return verdicts


def classify_file(
    file_path: str,
    text: str,
    gaps: Sequence[dict[str, Any]] = (),
    *,
    checklist_marker: str = "",
) -> VendorVerdict | None:
    """Classify one file from its path, content, and gap records."""
    # 1. Filename convention — independent corroboration by itself.
    suffix = _generated_suffix(file_path)
    if suffix:
        return VendorVerdict(
            kind=KIND_GENERATED,
            signal="extension",
            detail=f"generated-output filename ({suffix})",
            corroborated=True,
        )

    # 2. Generator banner (comment-anchored), including the inventory
    #    builder's own uncorroborated-marker flag from the checklist.
    banner = _banner_marker(text)
    signal = "banner"
    if not banner and checklist_marker:
        banner = "inventory generated-file marker"
        signal = "checklist"
    if banner:
        corroborated = generated_marker_corroborated(file_path)
        return VendorVerdict(
            kind=KIND_GENERATED,
            signal=signal,
            detail=(
                f"generator banner: {banner!r}"
                + (
                    " + generated-shaped path"
                    if corroborated
                    else " (uncorroborated — glance, never skip)"
                )
            ),
            corroborated=corroborated,
        )

    # 3. Vendored-provenance banner (upstream import pinned to a
    #    revision) — the vendoring convention of projects that copy
    #    dependencies flat into the tree instead of under vendor/
    #    directories, where the path convention below never fires.
    vendored_banner = _vendored_banner_marker(text)
    if vendored_banner:
        return VendorVerdict(
            kind=KIND_VENDORED,
            signal="banner",
            detail=f"vendored-provenance banner: {vendored_banner!r}",
        )

    # 4. Vendored-path convention.
    segment = _vendored_segment(file_path)
    if segment:
        return VendorVerdict(
            kind=KIND_VENDORED,
            signal="path",
            detail=f"vendored path segment {segment!r}",
        )

    # 5. Structural signatures (target-controlled — glance tier only).
    structure = _structure_detail(text, gaps)
    if structure:
        return VendorVerdict(
            kind=KIND_VENDORED,
            signal="structure",
            detail=structure,
        )

    return None


# ── Signal helpers ────────────────────────────────────────────────────


def _generated_suffix(file_path: str) -> str:
    name = PurePosixPath(file_path.replace("\\", "/")).name.lower()
    for suffix in _GENERATED_SUFFIXES:
        if name.endswith(suffix):
            return suffix
    return ""


def _vendored_segment(file_path: str) -> str:
    parts = PurePosixPath(file_path.replace("\\", "/")).parts
    for part in parts[:-1]:  # directory segments only
        if part.lower() in _VENDORED_SEGMENTS:
            return part
    return ""


def _banner_marker(text: str) -> str:
    """First generator-banner match inside a comment line within the
    header window, or "" when none. Anchored markers must start the
    comment text; floating markers may appear anywhere in the line."""
    if not text:
        return ""
    window = text[:_BANNER_MAX_BYTES]
    for raw in window.splitlines()[:_BANNER_MAX_LINES]:
        if not _COMMENT_RE.match(raw):
            continue
        comment_text = _COMMENT_LEADER_RE.sub("", raw)
        for marker in _ANCHORED_BANNER_MARKERS:
            m = marker.match(comment_text)
            if m:
                return m.group(0)[:60]
        for marker in _FLOATING_BANNER_MARKERS:
            m = marker.search(raw)
            if m:
                return m.group(0)[:60]
    return ""


def _vendored_banner_marker(text: str) -> str:
    """First vendored-provenance banner match inside a comment line
    within the header window, or "" when none. Anchored: the phrase
    must start the comment text, mirroring the generator banners."""
    if not text:
        return ""
    window = text[:_BANNER_MAX_BYTES]
    for raw in window.splitlines()[:_BANNER_MAX_LINES]:
        if not _COMMENT_RE.match(raw):
            continue
        comment_text = _COMMENT_LEADER_RE.sub("", raw)
        for marker in _VENDORED_BANNER_MARKERS:
            m = marker.match(comment_text)
            if m:
                return m.group(0)[:60]
    return ""


def _structure_detail(text: str, gaps: Sequence[dict[str, Any]]) -> str:
    if not text:
        return ""
    lines = text.splitlines()
    nonblank = [ln for ln in lines if ln.strip()]
    if not nonblank:
        return ""

    # Constant-table shape.
    table = sum(
        1
        for ln in nonblank
        if _TABLE_LINE_RE.match(ln) or _DEFINE_CONST_RE.match(ln)
    )
    if table >= _TABLE_MIN_LINES and table / len(nonblank) >= _TABLE_MIN_RATIO:
        return (
            f"constant-table shape ({table}/{len(nonblank)} "
            f"non-blank lines are table rows / constant defines)"
        )

    # One-liner-swarm shape (needs the per-function gap records).
    slocs = [
        _gap_sloc(g)
        for g in gaps
        if (g.get("kind") or "function") in _FUNCTION_KINDS
    ]
    if len(slocs) >= _SWARM_MIN_FUNCS:
        tiny = sum(1 for s in slocs if 0 <= s <= _SWARM_TINY_SLOC)
        comments = sum(1 for ln in nonblank if _COMMENT_RE.match(ln))
        if (
            tiny / len(slocs) >= _SWARM_TINY_FRACTION
            and comments / len(nonblank) <= _SWARM_MAX_COMMENT_FRACTION
        ):
            return (
                f"one-liner swarm ({tiny}/{len(slocs)} functions are "
                f"≤{_SWARM_TINY_SLOC} SLOC, "
                f"{comments}/{len(nonblank)} comment lines)"
            )
    return ""


def _gap_sloc(gap: dict[str, Any]) -> int:
    sloc = gap.get("sloc")
    if sloc is None:
        sloc = (gap.get("line_end", 0) or 0) - (gap.get("line_start", 0) or 0)
    try:
        return int(sloc)
    except (TypeError, ValueError):
        return -1


def _checklist_marker_flags(
    checklist: dict[str, Any] | None,
) -> dict[str, str]:
    """``{path: marker}`` for checklist file records the inventory
    builder flagged (``generated_marker: "uncorroborated"``)."""
    flags: dict[str, str] = {}
    if not checklist:
        return flags
    for rec in checklist.get("files") or []:
        if not isinstance(rec, dict):
            continue
        marker = rec.get("generated_marker")
        path = rec.get("path")
        if marker and path:
            flags[str(path)] = str(marker)
    return flags


def _read_file(file_path: str, target_path: Path | None) -> str:
    """Bounded, traversal-safe file read; "" on any failure."""
    if target_path is None:
        return ""
    resolved = safe_join(target_path, file_path)
    if resolved is None:
        return ""
    try:
        with open(resolved, "rb") as fh:
            raw = fh.read(_MAX_STRUCTURE_BYTES)
    except OSError:
        return ""
    return raw.decode("utf-8", errors="replace")
