"""Vendored/generated-code detector — hermetic fixture tests.

Positive fixtures: generator banners (protoc / Eurydice / KaRaMeL
shapes), generated-output filenames, vendored paths, generated-shape
structure (constant tables, one-liner swarms). Negative controls:
hand-written code with a big-but-not-dominant table, commented
hand-written headers, prose mentions of "generated" outside comments.
"""

from __future__ import annotations

from core.audit.vendored_detector import (
    KIND_GENERATED,
    KIND_VENDORED,
    VendorVerdict,
    classify_file,
    detect_vendored_files,
)


def _gap(file="a.c", name="f", line_start=1, sloc=3, kind="function"):
    return {
        "file": file,
        "name": name,
        "line_start": line_start,
        "line_end": line_start + sloc,
        "sloc": sloc,
        "kind": kind,
    }


# ── Banner detection ─────────────────────────────────────────────────


class TestBannerSignal:
    def test_protoc_banner(self):
        text = "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x\n"
        v = classify_file("api/types.go", text)
        assert v is not None
        assert v.kind == KIND_GENERATED
        assert v.signal == "banner"

    def test_eurydice_revision_block(self):
        text = (
            "/*\n"
            " * SPDX-License-Identifier: MIT or Apache-2.0\n"
            " *\n"
            " * This code was generated with the following revisions:\n"
            " * Charon: aaaa\n"
            " * Eurydice: bbbb\n"
            " * Karamel: cccc\n"
            " */\n"
            "static inline void f(void) {}\n"
        )
        v = classify_file("mlkem768.h", text)
        assert v is not None
        assert v.kind == KIND_GENERATED
        assert v.signal == "banner"

    def test_karamel_banner(self):
        text = "/* Generated by KaRaMeL v1.0 */\nint f(void) { return 0; }\n"
        v = classify_file("kremlib.h", text)
        assert v is not None
        assert v.kind == KIND_GENERATED

    def test_bindgen_banner(self):
        text = (
            "/* automatically generated by rust-bindgen 0.69.4 */\n"
            "pub struct Foo;\n"
        )
        v = classify_file("bindings.rs", text)
        assert v is not None
        assert v.kind == KIND_GENERATED

    def test_banner_below_license_block(self):
        license_block = "".join(
            f" * license line {i}\n" for i in range(30)
        )
        text = (
            "/*\n" + license_block + " */\n"
            "/* This file was generated by mkproto.sh — do not edit */\n"
            "int f(void);\n"
        )
        v = classify_file("proto.h", text)
        assert v is not None
        assert v.kind == KIND_GENERATED

    def test_banner_must_be_in_comment(self):
        # Prose/string mention never classifies (comment-anchored).
        text = (
            'static const char *msg = "report generated by the server";\n'
            "int f(void) { return 0; }\n"
        )
        assert classify_file("report.c", text) is None

    def test_prose_mention_mid_comment_not_a_banner(self):
        # Hand-written headers that DESCRIBE generated code: the
        # marker appears mid-sentence, not at the comment start.
        # (Real shapes that a floating match wrongly classified.)
        text = (
            "// Notes on the wire protocol\n"
            "// (which is also its wire format).  Code generated by the\n"
            "// compiler uses these classes.\n"
            "struct Reader { int x; };\n"
        )
        assert classify_file("layout.h", text) is None

    def test_prose_events_doc_comment_not_a_banner(self):
        text = (
            "package events\n"
            "// Events is pubsub channel for events generated by the "
            "engine.\n"
            "type Events struct{}\n"
        )
        assert classify_file("events.go", text) is None

    def test_banner_outside_window_ignored(self):
        text = ("int line(void);\n" * 200) + "// generated by tool\n"
        assert classify_file("big.c", text) is None

    def test_uncorroborated_banner_not_skip_eligible(self):
        # Root-level file, banner only: glance-bound, never skip.
        text = "/* Generated by Eurydice */\nvoid f(void) {}\n"
        v = classify_file("mlkem768.h", text)
        assert v is not None
        assert v.corroborated is False
        assert "uncorroborated" in v.detail

    def test_corroborated_banner_skip_eligible(self):
        # Banner + generated-shaped path segment = house corroboration.
        text = "/* Generated by protoc. DO NOT EDIT. */\nvoid f(void) {}\n"
        v = classify_file("gen/wire.c", text)
        assert v is not None
        assert v.corroborated is True


# ── Filename / path conventions ──────────────────────────────────────


class TestNameAndPathSignals:
    def test_generated_extensions(self):
        for name in (
            "schema_pb2.py", "rpc_pb2_grpc.py", "wire.pb.go",
            "msg.pb.h", "msg.pb.cc", "proto.pb-c.c",
            "models_generated.rs", "view.g.dart", "lex.yy.c",
        ):
            v = classify_file(name, "")
            assert v is not None, name
            assert v.kind == KIND_GENERATED
            assert v.signal == "extension"
            assert v.corroborated is True

    def test_vendored_path_segments(self):
        for path in (
            "vendor/zlib/inflate.c",
            "third_party/lib/x.py",
            "external/pkg/y.go",
            "node_modules/left-pad/index.js",
            "src/deps/miniz/miniz.c",
            "subprojects/glib/gutils.c",
        ):
            v = classify_file(path, "int f(void) { return g(); }\n")
            assert v is not None, path
            assert v.kind == KIND_VENDORED
            assert v.signal == "path"

    def test_filename_named_vendor_is_not_vendored(self):
        # Directory segments only — a FILE named vendor.c is first-party.
        assert classify_file("src/vendor.c", "int f(void) {}\n") is None

    def test_banner_in_vendor_path_prefers_generated(self):
        text = "// Code generated by protoc. DO NOT EDIT.\n"
        v = classify_file("vendor/pb/x.go", text)
        assert v is not None
        assert v.kind == KIND_GENERATED
        assert v.corroborated is True  # vendor/ is a corroborating hint


# ── Structural signatures ────────────────────────────────────────────


def _define_table(n):
    return "".join(f"#define CKM_MECH_{i} 0x{i:08x}\n" for i in range(n))


def _numeric_table(n):
    return "".join(f"  0x{i:02x}, 0x{i + 1:02x}, 0x{i + 2:02x},\n" for i in range(n))


class TestStructureSignal:
    def test_pkcs11_style_define_catalog(self):
        text = (
            "/* PKCS #11 mechanism constants */\n"
            "#ifndef PKCS11_H\n#define PKCS11_H\n"
            + _define_table(400)
            + "typedef unsigned long CK_RV;\n#endif\n"
        )
        v = classify_file("pkcs11.h", text)
        assert v is not None
        assert v.kind == KIND_VENDORED
        assert v.signal == "structure"
        assert "constant-table" in v.detail

    def test_numeric_table_file(self):
        text = "static const unsigned char tbl[] = {\n" + _numeric_table(
            300
        ) + "};\n"
        v = classify_file("tables.c", text)
        assert v is not None
        assert v.kind == KIND_VENDORED
        assert v.signal == "structure"

    def test_one_liner_swarm(self):
        funcs = "".join(
            f"static inline int get_{i}(ctx_t *c) {{ return c->f{i}; }}\n"
            for i in range(50)
        )
        gaps = [
            _gap(file="swarm.h", name=f"get_{i}", line_start=i + 1, sloc=1)
            for i in range(50)
        ]
        v = classify_file("swarm.h", funcs, gaps)
        assert v is not None
        assert v.kind == KIND_VENDORED
        assert "one-liner swarm" in v.detail

    def test_negative_handwritten_code_with_big_table(self):
        # Real hand-written code that CONTAINS a big table must NOT
        # classify: the table does not dominate the file.
        code_lines = "".join(
            f"static int helper_{i}(int x) {{\n"
            f"    /* clamp and translate opcode {i} */\n"
            f"    if (x < 0) return -1;\n"
            f"    return x + {i};\n"
            f"}}\n"
            for i in range(80)
        )
        text = (
            "/* opcode translation, hand-maintained */\n"
            "static const int opcodes[] = {\n"
            + _numeric_table(120)
            + "};\n"
            + code_lines
        )
        assert classify_file("opcodes.c", text) is None

    def test_negative_commented_accessor_header(self):
        # Tiny functions but healthy comment density: hand-written.
        funcs = "".join(
            f"/* Returns field {i}; caller must hold the lock. */\n"
            f"static inline int get_{i}(ctx_t *c) {{ return c->f{i}; }}\n"
            for i in range(50)
        )
        gaps = [
            _gap(file="acc.h", name=f"get_{i}", line_start=2 * i + 2, sloc=1)
            for i in range(50)
        ]
        assert classify_file("acc.h", funcs, gaps) is None

    def test_negative_few_functions(self):
        funcs = "".join(
            f"static inline int get_{i}(ctx_t *c) {{ return c->f{i}; }}\n"
            for i in range(10)
        )
        gaps = [
            _gap(file="small.h", name=f"get_{i}", line_start=i + 1, sloc=1)
            for i in range(10)
        ]
        assert classify_file("small.h", funcs, gaps) is None

    def test_negative_ordinary_source(self):
        text = (
            "/* session teardown */\n"
            "int close_session(session_t *s) {\n"
            "    if (!s) return -1;\n"
            "    free(s->buf);\n"
            "    free(s);\n"
            "    return 0;\n"
            "}\n"
        )
        assert classify_file("session.c", text, [_gap(sloc=6)]) is None


# ── detect_vendored_files (file IO path) ─────────────────────────────


class TestDetectVendoredFiles:
    def test_reads_target_files(self, tmp_path):
        gen = tmp_path / "wire.c"
        gen.write_text(
            "/* Code generated by protoc-c. DO NOT EDIT. */\n"
            "int wire_f(void) { return 0; }\n"
        )
        hand = tmp_path / "main.c"
        hand.write_text(
            "/* entry point */\nint main(void) { return wire_f(); }\n"
        )
        gaps = [
            _gap(file="wire.c", name="wire_f"),
            _gap(file="main.c", name="main"),
        ]
        verdicts = detect_vendored_files(gaps, target_path=tmp_path)
        assert set(verdicts) == {"wire.c"}
        assert verdicts["wire.c"].kind == KIND_GENERATED

    def test_checklist_marker_consumed(self, tmp_path):
        # Inventory flagged the file; no re-read needed.
        gaps = [_gap(file="gen.c", name="f")]
        checklist = {
            "files": [{"path": "gen.c", "generated_marker": "uncorroborated"}],
        }
        verdicts = detect_vendored_files(
            gaps, target_path=tmp_path, checklist=checklist,
        )
        assert verdicts["gen.c"].kind == KIND_GENERATED
        assert verdicts["gen.c"].signal == "checklist"
        assert verdicts["gen.c"].corroborated is False

    def test_traversal_rejected(self, tmp_path):
        gaps = [_gap(file="../outside.c", name="f")]
        # No crash; path has no vendored segment and cannot be read.
        assert detect_vendored_files(gaps, target_path=tmp_path) == {}

    def test_unreadable_file_no_crash(self, tmp_path):
        gaps = [_gap(file="missing.c", name="f")]
        assert detect_vendored_files(gaps, target_path=tmp_path) == {}

    def test_no_target_path_path_signals_still_apply(self):
        gaps = [_gap(file="vendor/z/x.c", name="f")]
        verdicts = detect_vendored_files(gaps)
        assert verdicts["vendor/z/x.c"].kind == KIND_VENDORED

    def test_verdict_is_frozen(self):
        v = VendorVerdict(kind=KIND_VENDORED, signal="path", detail="d")
        try:
            v.kind = "generated"  # type: ignore[misc]
        except AttributeError:
            pass
        else:  # pragma: no cover
            raise AssertionError("VendorVerdict must be frozen")
