"""Vendored/generated triage tier — routing and audit-trail tests.

Routing contract (see core.audit.vendored_detector docstring):
corroborated generated files → SKIP; uncorroborated banners and all
structural/path evidence → GLANCE; boundary-adjacent functions never
skip; pinned gaps are untouched. Every skip/glance decision leaves a
suppressions.jsonl record and the run summary carries the counts.
"""

from __future__ import annotations

import json

from core.audit.triage import (
    TriageBucket,
    classify_all,
    classify_function,
    vendor_decision,
)
from core.audit.vendored_detector import (
    KIND_GENERATED,
    KIND_VENDORED,
    VendorVerdict,
    detect_vendored_files,
)


def _gap(file="wire.c", name="f", line_start=10, sloc=3, **kw):
    g = {
        "file": file,
        "name": name,
        "line_start": line_start,
        "line_end": line_start + sloc,
        "sloc": sloc,
        "kind": "function",
    }
    g.update(kw)
    return g


def _generated(corroborated=True):
    return VendorVerdict(
        kind=KIND_GENERATED,
        signal="banner",
        detail="generator banner: 'Generated by protoc'",
        corroborated=corroborated,
    )


def _vendored():
    return VendorVerdict(
        kind=KIND_VENDORED,
        signal="path",
        detail="vendored path segment 'third_party'",
    )


class TestClassifyFunctionRouting:
    def test_corroborated_generated_skips(self):
        tr = classify_function(
            file="gen/wire.c", function="f", sloc=3,
            vendor_verdict=_generated(corroborated=True),
        )
        assert tr.bucket == TriageBucket.SKIP
        assert vendor_decision(tr) == "skip"

    def test_uncorroborated_banner_glances_never_skips(self):
        # Anti-evasion: the banner is target-controlled text — alone
        # it never buys invisibility, only the cheap glance tier.
        tr = classify_function(
            file="mlkem768.h", function="f", sloc=3,
            vendor_verdict=_generated(corroborated=False),
        )
        assert tr.bucket == TriageBucket.GLANCE
        assert vendor_decision(tr) == "glance"

    def test_generated_entry_point_glances(self):
        tr = classify_function(
            file="gen/wire.c", function="f", sloc=3,
            is_entry_point=True,
            vendor_verdict=_generated(corroborated=True),
        )
        assert tr.bucket == TriageBucket.GLANCE
        assert vendor_decision(tr) == "glance"

    def test_generated_sink_glances(self):
        tr = classify_function(
            file="gen/wire.c", function="f", sloc=3,
            is_sink=True,
            vendor_verdict=_generated(corroborated=True),
        )
        assert tr.bucket == TriageBucket.GLANCE

    def test_vendored_glances(self):
        # A 100-SLOC vendored function would normally be INVESTIGATE.
        tr = classify_function(
            file="third_party/z.c", function="f", sloc=100,
            vendor_verdict=_vendored(),
        )
        assert tr.bucket == TriageBucket.GLANCE
        assert vendor_decision(tr) == "glance"

    def test_vendored_boundary_keeps_normal_routing(self):
        tr = classify_function(
            file="third_party/z.c", function="f", sloc=100,
            is_trust_boundary=True,
            vendor_verdict=_vendored(),
        )
        assert tr.bucket == TriageBucket.DEEP_DIVE
        assert vendor_decision(tr) is None

    def test_vendored_joern_flow_keeps_normal_routing(self):
        tr = classify_function(
            file="third_party/z.c", function="f", sloc=100,
            has_joern_flows=True,
            vendor_verdict=_vendored(),
        )
        assert tr.bucket == TriageBucket.DEEP_DIVE

    def test_no_verdict_normal_routing(self):
        tr = classify_function(file="a.c", function="f", sloc=100)
        assert tr.bucket == TriageBucket.INVESTIGATE
        assert vendor_decision(tr) is None

    def test_binary_absent_wins_over_vendor(self):
        # Oracle-earned dead-code skip stays the stronger verdict.
        tr = classify_function(
            file="gen/wire.c", function="f", sloc=3,
            binary_absent=True,
            vendor_verdict=_generated(corroborated=True),
        )
        assert tr.bucket == TriageBucket.SKIP
        assert any("binary_oracle_absent" in r for r in tr.reasons)
        assert vendor_decision(tr) is None


class TestClassifyAllGuards:
    def test_pinned_gap_exempt(self):
        gaps = [_gap(name="f", pinned=True), _gap(name="g", line_start=50, sloc=100)]
        results = classify_all(
            gaps,
            vendor_verdicts={"wire.c": _generated(corroborated=True)},
        )
        pinned = results["wire.c:f:10"]
        assert vendor_decision(pinned) is None
        assert pinned.bucket != TriageBucket.SKIP or not any(
            r.startswith("generated code") for r in pinned.reasons
        )
        # Unpinned sibling in the same file IS routed.
        assert vendor_decision(results["wire.c:g:50"]) == "skip"

    def test_force_review_gap_exempt(self):
        gaps = [_gap(name="f", force_review=True)]
        results = classify_all(
            gaps,
            vendor_verdicts={"wire.c": _generated(corroborated=True)},
        )
        assert vendor_decision(results["wire.c:f:10"]) is None

    def test_entry_point_key_glances(self):
        gaps = [_gap(name="f")]
        results = classify_all(
            gaps,
            entry_points=frozenset({"wire.c:f"}),
            vendor_verdicts={"wire.c": _generated(corroborated=True)},
        )
        assert results["wire.c:f:10"].bucket == TriageBucket.GLANCE

    def test_no_verdicts_no_change(self):
        gaps = [_gap(name="f", sloc=100)]
        results = classify_all(gaps, vendor_verdicts=None)
        assert results["wire.c:f:10"].bucket == TriageBucket.INVESTIGATE


class TestOrchestratorIntegration:
    """End-to-end through the triage layer: detection on a real tree,
    suppression records written, review-loop skip honored without an
    LLM call."""

    def _target(self, tmp_path):
        target = tmp_path / "target"
        target.mkdir()
        gen_dir = target / "gen"
        gen_dir.mkdir()
        (gen_dir / "wire.c").write_text(
            "/* Code generated by protoc-c. DO NOT EDIT. */\n"
            "int wire_get(int i) { return i; }\n"
        )
        (target / "main.c").write_text(
            "/* entry */\nint main(void) { return wire_get(1); }\n"
        )
        return target

    def test_records_written_and_skip_honored(self, tmp_path):
        from core.audit.orchestrator import (
            OrchestratorConfig,
            OrchestratorResult,
            _record_vendored_suppressions,
            review_one_function,
        )
        from core.audit.shared_state import SharedState

        target = self._target(tmp_path)
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        gaps = [
            _gap(file="gen/wire.c", name="wire_get", line_start=2, sloc=1),
            _gap(file="main.c", name="main", line_start=2, sloc=1),
        ]

        verdicts = detect_vendored_files(gaps, target_path=target)
        assert set(verdicts) == {"gen/wire.c"}
        assert verdicts["gen/wire.c"].corroborated is True

        triage = classify_all(gaps, vendor_verdicts=verdicts)
        assert triage["gen/wire.c:wire_get:2"].bucket == TriageBucket.SKIP

        skipped, glanced = _record_vendored_suppressions(
            gaps, triage, verdicts, out_dir,
        )
        assert (skipped, glanced) == (1, 0)

        records = [
            json.loads(line)
            for line in (out_dir / "suppressions.jsonl")
            .read_text().splitlines()
            if line.strip()
        ]
        assert len(records) == 1
        rec = records[0]
        assert rec["rule_id"] == "audit:vendored-triage"
        assert rec["file_path"] == "gen/wire.c"
        assert rec["function"] == "wire_get"
        assert rec["line"] == 2
        assert rec["verdict"] == "generated_code"
        assert rec["dropped"] is False
        assert rec["stage"] == "hypothesis-triage"
        assert rec["tier"] == "skip"
        assert rec["signal"] == "banner"
        assert "reason" in rec

        # Skip honored through the review loop: no LLM call happens.
        config = OrchestratorConfig(target_path=target, out_dir=out_dir)
        shared = SharedState(triage_results=triage)
        result = OrchestratorResult()
        calls: list = []

        def review_fn(*a, **kw):  # pragma: no cover - must not run
            calls.append(1)
            raise AssertionError("LLM review ran for a vendored skip")

        outcome = review_one_function(
            gaps[0], shared, config, review_fn, result,
        )
        assert calls == []
        assert outcome.status == "clean"
        assert "generated code" in outcome.body
        assert outcome.evidence_tool == "triage:classifier"

    def test_glance_decision_recorded(self, tmp_path):
        from core.audit.orchestrator import _record_vendored_suppressions

        out_dir = tmp_path / "out"
        out_dir.mkdir()
        gaps = [_gap(file="third_party/z.c", name="f", sloc=40)]
        verdicts = {"third_party/z.c": _vendored()}
        triage = classify_all(gaps, vendor_verdicts=verdicts)
        assert triage["third_party/z.c:f:10"].bucket == TriageBucket.GLANCE

        skipped, glanced = _record_vendored_suppressions(
            gaps, triage, verdicts, out_dir,
        )
        assert (skipped, glanced) == (0, 1)
        rec = json.loads(
            (out_dir / "suppressions.jsonl").read_text().splitlines()[0]
        )
        assert rec["verdict"] == "vendored_code"
        assert rec["tier"] == "glance"
        assert rec["dropped"] is False

    def test_no_decision_no_record(self, tmp_path):
        from core.audit.orchestrator import _record_vendored_suppressions

        out_dir = tmp_path / "out"
        out_dir.mkdir()
        # Boundary-adjacent vendored: normal routing, no record.
        gaps = [_gap(file="third_party/z.c", name="f", sloc=40)]
        verdicts = {"third_party/z.c": _vendored()}
        triage = classify_all(
            gaps,
            trust_boundaries=frozenset({"third_party/z.c:f"}),
            vendor_verdicts=verdicts,
        )
        skipped, glanced = _record_vendored_suppressions(
            gaps, triage, verdicts, out_dir,
        )
        assert (skipped, glanced) == (0, 0)
        assert not (out_dir / "suppressions.jsonl").exists()

    def test_run_summary_counts(self, tmp_path):
        from core.audit.report import _format_summary, _load_vendored_triage

        out_dir = tmp_path / "out"
        out_dir.mkdir()
        rows = [
            {"rule_id": "audit:vendored-triage", "tier": "skip"},
            {"rule_id": "audit:vendored-triage", "tier": "skip"},
            {"rule_id": "audit:vendored-triage", "tier": "glance"},
            # Foreign writer rows must not count.
            {"rule_id": "audit:hypothesis-triage",
             "verdict": "binary_oracle_absent"},
        ]
        (out_dir / "suppressions.jsonl").write_text(
            "".join(json.dumps(r) + "\n" for r in rows)
        )
        counts = _load_vendored_triage(out_dir)
        assert counts == {"skipped": 2, "glanced": 1}

        summary = _format_summary(
            {"stats": {}, "vendored_triage": counts},
        )
        assert "Vendored/generated triage: 2 functions skipped" in summary
        assert "1 routed to glance" in summary

    def test_run_summary_absent_when_no_decisions(self, tmp_path):
        from core.audit.report import _load_vendored_triage

        out_dir = tmp_path / "out"
        out_dir.mkdir()
        assert _load_vendored_triage(out_dir) == {}

    def test_detection_gate_respects_config(self, tmp_path):
        from core.audit.orchestrator import (
            OrchestratorConfig,
            _vendored_triage_verdicts,
        )

        target = self._target(tmp_path)
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        gaps = [_gap(file="gen/wire.c", name="wire_get", line_start=2, sloc=1)]

        on = OrchestratorConfig(target_path=target, out_dir=out_dir)
        assert "gen/wire.c" in _vendored_triage_verdicts(on, gaps)

        off = OrchestratorConfig(
            target_path=target, out_dir=out_dir, vendored_triage=False,
        )
        assert _vendored_triage_verdicts(off, gaps) == {}

    def test_checklist_marker_feeds_detection(self, tmp_path):
        # The inventory builder's own uncorroborated-generated flag is
        # consumed without re-reading the file.
        from core.audit.orchestrator import (
            OrchestratorConfig,
            _vendored_triage_verdicts,
        )

        target = tmp_path / "target"
        target.mkdir()
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        gaps = [_gap(file="mystery.c", name="f")]
        checklist = {
            "files": [
                {"path": "mystery.c", "generated_marker": "uncorroborated"},
            ],
        }
        config = OrchestratorConfig(target_path=target, out_dir=out_dir)
        verdicts = _vendored_triage_verdicts(config, gaps, checklist=checklist)
        assert verdicts["mystery.c"].kind == KIND_GENERATED
        assert verdicts["mystery.c"].corroborated is False


class TestFlagThreading:
    """--no-vendored-triage: AuditPipelineOpts → OrchestratorConfig."""

    class _StubClient:
        class config:  # noqa: D106 — attribute bag
            max_cost_per_scan = 10.0

    def _build(self, opts):
        from core.audit.pipeline import ReviewMode, _build_orchestrator_config

        return _build_orchestrator_config(
            opts, self._StubClient(), ["default"], ReviewMode.SECURITY,
        )

    def test_default_on(self, tmp_path):
        from core.audit.pipeline import AuditPipelineOpts

        opts = AuditPipelineOpts(
            target_path=tmp_path, out_dir=tmp_path / "out",
        )
        assert self._build(opts).vendored_triage is True

    def test_flag_disables(self, tmp_path):
        from core.audit.pipeline import AuditPipelineOpts

        opts = AuditPipelineOpts(
            target_path=tmp_path, out_dir=tmp_path / "out",
            vendored_triage=False,
        )
        assert self._build(opts).vendored_triage is False
