"""Tests for the yarn.lock parser (classic v1 + Berry v2+)."""

from __future__ import annotations

from pathlib import Path

from packages.sca.models import PinStyle
from packages.sca.parsers.yarn_lock import parse


def _write(tmp_path: Path, body: str) -> Path:
    p = tmp_path / "yarn.lock"
    p.write_text(body, encoding="utf-8")
    return p


# ---------------------------------------------------------------------------
# Classic v1
# ---------------------------------------------------------------------------

def test_classic_basic(tmp_path: Path) -> None:
    body = """\
# THIS IS AN AUTOGENERATED FILE.
# yarn lockfile v1


lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#abcdef"
  integrity sha512-xxx

"@types/node@^20.5.0", "@types/node@^20.10.0":
  version "20.10.5"
  resolved "https://registry.yarnpkg.com/@types/node/-/node-20.10.5.tgz#xx"
"""
    deps = {d.name: d for d in parse(_write(tmp_path, body))}
    assert deps["lodash"].version == "4.17.21"
    assert deps["lodash"].pin_style is PinStyle.EXACT
    assert deps["lodash"].is_lockfile is True
    assert deps["@types/node"].version == "20.10.5"


def test_classic_git_resolved(tmp_path: Path) -> None:
    body = """\
# yarn lockfile v1

forked@git+https://github.com/u/x.git#abc:
  version "0.0.0"
  resolved "git+https://github.com/u/x.git#abc"
"""
    deps = parse(_write(tmp_path, body))
    assert deps[0].pin_style is PinStyle.GIT


# ---------------------------------------------------------------------------
# Berry v2+
# ---------------------------------------------------------------------------

def test_berry_yaml_format(tmp_path: Path) -> None:
    body = """\
__metadata:
  version: 6
  cacheKey: 8

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: abc
  languageName: node
  linkType: hard

"@types/node@npm:^20.5.0":
  version: 20.10.5
  resolution: "@types/node@npm:20.10.5"
  linkType: hard
"""
    deps = {d.name: d for d in parse(_write(tmp_path, body))}
    assert deps["lodash"].version == "4.17.21"
    assert deps["lodash"].pin_style is PinStyle.EXACT
    assert deps["@types/node"].version == "20.10.5"


def test_berry_workspace_resolution(tmp_path: Path) -> None:
    body = """\
__metadata:
  version: 6

"my-pkg@workspace:packages/my-pkg":
  version: 0.0.0-use.local
  resolution: "my-pkg@workspace:packages/my-pkg"
  languageName: unknown
  linkType: soft
"""
    deps = parse(_write(tmp_path, body))
    assert len(deps) == 1
    assert deps[0].name == "my-pkg"
    assert deps[0].pin_style is PinStyle.PATH


def test_classic_block_with_only_specs_no_version(tmp_path: Path) -> None:
    body = """\
# yarn lockfile v1

ghost@^1.0:
  resolved "https://example.com/ghost.tgz"
"""
    deps = parse(_write(tmp_path, body))
    assert len(deps) == 1
    assert deps[0].version is None
    assert deps[0].pin_style is PinStyle.WILDCARD


def test_empty_file_returns_empty(tmp_path: Path) -> None:
    deps = parse(_write(tmp_path, ""))
    assert deps == []


def test_classic_scoped_with_complex_range(tmp_path: Path) -> None:
    body = """\
# yarn lockfile v1

"@babel/core@^7.0.0", "@babel/core@^7.5.0":
  version "7.23.0"
"""
    deps = parse(_write(tmp_path, body))
    assert deps[0].name == "@babel/core"
    assert deps[0].version == "7.23.0"


def test_sniff_value_error_falls_back_to_classic(tmp_path: Path) -> None:
    """yaml.safe_load raises ValueError on out-of-range date scalars —
    the Berry sniff must treat that as "not Berry" and the classic
    parser must still extract the deps (a raise here used to escape to
    the dispatch catch-all: whole lockfile read as zero deps)."""
    body = """\
"lodash@^4.17.21":
  version "4.17.21"
release: 2023-99-99
"""
    deps = parse(_write(tmp_path, body))
    assert [d.name for d in deps if d.name == "lodash"] == ["lodash"]
    assert deps[0].version == "4.17.21"


def test_berry_value_error_returns_empty_with_no_raise(
    tmp_path: Path,
) -> None:
    """A genuinely Berry file (__metadata) with a ValueError-raising
    scalar reports a parse failure ([]), it must not raise."""
    body = """\
__metadata:
  version: 8

"left-pad@npm:^1.0.0":
  version: 1.3.0
  released: 2023-99-99
"""
    deps = parse(_write(tmp_path, body))
    assert deps == []


# ---------------------------------------------------------------------------
# npm: alias descriptors resolve to the installed package
# ---------------------------------------------------------------------------

def test_classic_alias_resolves_to_real_package(tmp_path: Path) -> None:
    # ``"myalias@npm:realpkg@^1.0"`` installs realpkg — OSV must be
    # queried for realpkg, not the alias, or the installed package's
    # advisories are invisible.
    body = (
        "# yarn lockfile v1\n\n"
        '"myalias@npm:realpkg@^1.0.0":\n'
        '  version "1.0.2"\n'
        '  resolved "https://registry.yarnpkg.com/realpkg/-/realpkg-1.0.2.tgz"\n'
    )
    p = tmp_path / "yarn.lock"
    p.write_text(body, encoding="utf-8")
    [d] = parse(p)
    assert d.name == "realpkg"
    assert d.version == "1.0.2"


def test_berry_alias_resolves_to_real_scoped_package(tmp_path: Path) -> None:
    body = (
        "__metadata:\n"
        "  version: 8\n"
        '"myalias@npm:@scope/real@^1.0":\n'
        '  version: 1.4.0\n'
        '  resolution: "@scope/real@npm:1.4.0"\n'
    )
    p = tmp_path / "yarn.lock"
    p.write_text(body, encoding="utf-8")
    [d] = parse(p)
    assert d.name == "@scope/real"
    assert d.version == "1.4.0"


def test_plain_berry_protocol_descriptor_keeps_name(tmp_path: Path) -> None:
    # Other direction: ``lodash@npm:^4.17.21`` is the ordinary Berry
    # protocol form (range after ``npm:``), NOT an alias — the name
    # must stay lodash.
    body = (
        "__metadata:\n"
        "  version: 8\n"
        '"lodash@npm:^4.17.21":\n'
        '  version: 4.17.21\n'
        '  resolution: "lodash@npm:4.17.21"\n'
    )
    p = tmp_path / "yarn.lock"
    p.write_text(body, encoding="utf-8")
    [d] = parse(p)
    assert d.name == "lodash"
    assert d.version == "4.17.21"
