"""
Shared constants for discovery: GitHub mirrors and tracker-repo regexes.

Ported from code-differ/packages/patch_analysis/constants.py (v5.0+ lineage).

GITHUB_MIRRORS — When a canonical repo URL points to a non-GitHub host but a
GitHub mirror exists, we prefer the mirror (clone reliability + rate limits).
44 entries at port time.

TRACKER_REPO_PATTERNS — Regex patterns identifying repos that *collect* CVEs
rather than *hosting* the vulnerable code. Discoverers that return a tracker
must be filtered out before they reach acquisition. 79 entries at port time.
"""

from __future__ import annotations

GITHUB_MIRRORS: dict[str, str] = {
    "git.tukaani.org/xz": "https://github.com/tukaani-project/xz",
    "git.sv.nongnu.org/lzip": "https://github.com/lzip/lzip",
    "zlib.net": "https://github.com/madler/zlib",
    "git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux": "https://github.com/torvalds/linux",
    "git.kernel.org/pub/scm/linux/kernel/git/stable/linux": "https://github.com/torvalds/linux",
    "git.kernel.org": "https://github.com/torvalds/linux",
    "git.savannah.gnu.org/git/bash": "https://github.com/gitGNU/gnu_bash",
    "git.savannah.gnu.org/git/glibc": "https://github.com/bminor/glibc",
    "git.savannah.gnu.org/git/coreutils": "https://github.com/coreutils/coreutils",
    "git.savannah.gnu.org/git/binutils": "https://github.com/bminor/binutils-gdb",
    "git.savannah.gnu.org/git/grep": "https://github.com/gitGNU/gnu_grep",
    "git.savannah.gnu.org/git/sed": "https://github.com/gitGNU/gnu_sed",
    "git.savannah.gnu.org/git/tar": "https://github.com/gitGNU/gnu_tar",
    "git.openssl.org/openssl": "https://github.com/openssl/openssl",
    "git.openssl.org": "https://github.com/openssl/openssl",
    "git.gnupg.org/gnupg": "https://github.com/gpg/gnupg",
    "git.gnupg.org/libgcrypt": "https://github.com/gpg/libgcrypt",
    "git.haproxy.org/git/haproxy": "https://github.com/haproxy/haproxy",
    "git.haproxy.org": "https://github.com/haproxy/haproxy",
    "github.com/curl/curl": "https://github.com/curl/curl",
    "hg.nginx.org/nginx": "https://github.com/nginx/nginx",
    "nginx.org": "https://github.com/nginx/nginx",
    "svn.apache.org": "https://github.com/apache",
    "gitbox.apache.org/repos/asf/httpd": "https://github.com/apache/httpd",
    "gitbox.apache.org/repos/asf/apr": "https://github.com/apache/apr",
    "gitbox.apache.org/repos/asf/tomcat": "https://github.com/apache/tomcat",
    "anongit.mindrot.org/openssh": "https://github.com/openssh/openssh-portable",
    "cgit.freedesktop.org/systemd": "https://github.com/systemd/systemd",
    "cgit.freedesktop.org/xorg": "https://github.com/xorg",
    "git.postgresql.org": "https://github.com/postgres/postgres",
    "git.postgresql.org/git/postgresql": "https://github.com/postgres/postgres",
    "github.com/redis/redis": "https://github.com/redis/redis",
    "git.php.net": "https://github.com/php/php-src",
    "hg.python.org": "https://github.com/python/cpython",
    "github.com/python/cpython": "https://github.com/python/cpython",
    "perl5.git.perl.org": "https://github.com/perl/perl5",
    "git.ruby-lang.org": "https://github.com/ruby/ruby",
    "git.git.git": "https://github.com/git/git",
    "git.ffmpeg.org/ffmpeg": "https://github.com/FFmpeg/FFmpeg",
    "git.videolan.org/vlc": "https://github.com/videolan/vlc",
    "chromium.googlesource.com/webm/libwebp": "https://github.com/webmproject/libwebp",
    "git.busybox.net/busybox": "https://github.com/mirror/busybox",
    "sourceware.org/git/glibc": "https://github.com/bminor/glibc",
    "sourceware.org/git/binutils": "https://github.com/bminor/binutils-gdb",
}


TRACKER_REPO_PATTERNS: tuple[str, ...] = (
    r"^trickest/cve",
    r"^cveproject/",
    r"^CVEProject/",
    r"^nomi-sec/",
    r"^Threekiii/",
    r"^nu11secur1ty/",
    r"advisory|advisories",
    r"security-bulletin",
    r"vulnerability|vulns?$",
    r"vul-source",
    r"cve-\d{4}",
    r"/cve$",
    r"^[^/]+/cve$",
    r"exploit|poc",
    r"nuclei-templates",
    r"awesome-poc",
    r"^nvd",
    r"^osv",
    r"^witchcraze/",
    r"^XiaomingX/",
    r"^MrWQ/",
    r"^coffeehb/",
    r"^arschlochnop/",
    r"^gelusus/",
    r"^oscs1024/",
    r"^k8gege/",
    r"^Ascotbe/",
    r"^yevh/",
    r"^myh0st/",
    r"^adysec/",
    r"^canonical/ubuntu-security",
    r"^redhat-security",
    r"^vulnwatchdog",
    r"hacktricks",
    r"-wiki$",
    r"security-notices",
    r"threat-hunting",
    r"hunting-queries",
    r"sigma-rules",
    r"yara-rules",
    r"detection-rules",
    r"^projectdiscovery/",
    r"pentesting|pentest",
    r"^Ladon",
    r"security-scan",
    r"vuln-scan",
    r"cve-analysis",
    r"security-research",
    r"^Breaking",
    r"breaking.*ecdsa",
    r"breaking.*crypto",
    r"^daedalus/",
    r"LLL.*attack|attack.*LLL",
    r"cvelistv5",
    r"cveServices",
    r"cve_reports",
    r"cve-reports",
    r"^gitsec/",
    r"^enisaeu/",
    r"^test/repo$",
    # Added 2026-04-19 after Phase 2 gate audit: writeup / reproduction
    # / CVE-catalog / packaging slugs observed landing on real diffs but
    # never on upstream fix code.
    r"(?i)cvelist$",
    r"(?i)cve-list$",
    r"cybersecurity-fundamentals",
    r"risk-assessment",
    r"^vulhub(/|$)",
    r"(?i)ProjectDiscover-",
    r"-nucleitemplates",
    r"^openela-",
    r"^docker-hardened-images/",
    r"nixpkgs",
    r"-writeup",
    r"writeups?$",
)
